### ISSUE TITLE
I was testing and it got me banned.

### ISSUE THREAD

**Issue by zbtzsscript** [9xw/discord-mass-ban#3]
I was testing in a small server and it got me banned from discord. I got an email and it said "Reset your password" (Thats what it does when it thinks ur self-botting) Then got an email saying disabled.

**Comment by qro** [comment]
There is a minor limitation when using the user option with the mass-ban. You can't ban over 500 members in a server, otherwise this will result your account being disabled. After all discord doesn't allow selfbotting on their platform so next time use an alternative account. 

This is not an issue with the code.
